name: BIJOU'S FASHIONS
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4f9abb5-eacd-46a9-9dce-4e7096397a85.jpg
layout_spectrum: 0.1844101424794644
typography_spectrum: 0.7149277641437948
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: 'https://m.facebook.com/BijousFashions/'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/755b1ecf-ff98-4ace-a9f1-cce3388393ab.jpg
color:
  brandColors:
    - '#f4f4f4'
    - '#090b08'
    - '#30322d'
    - '#87a0c6'
    - '#d6c1d4'
  brandStrength: 0.7853818305302411
  lightness: 0.26302918535657227
  saturation: 0.375
  rhythmicContrast: 0.5880552039016038
purpose: []
title: Bijou's is the Seamless Merger of you and Elegant Accessories
author:
  name: Davie Hodge
  url: ''
  email: ''
content_rating:
  adult: false
