layout_spectrum: 0.9507777405732154
typography_spectrum: 0.28678773314950273
color:
  brandColors:
    - '#000000'
    - '#E4BC81'
    - '#C28453'
    - '#007265'
    - '#CD1F16'
  brandStrength: 0.47471338055714374
  lightness: 0.1988473402083584
  saturation: 0.11936995880300234
  rhythmicContrast: 0.009326572366298573
name: BIJOU'S FASHIONS
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4f9abb5-eacd-46a9-9dce-4e7096397a85.jpg
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: 'https://m.facebook.com/BijousFashions/'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/755b1ecf-ff98-4ace-a9f1-cce3388393ab.jpg
purpose:
  - type: contact
    url: 'mailto:sheena@bijousfashions.biz'
    label: Contact me
title: Bijou's is the Seamless Merger of you and Elegant Accessories
description: ''
author:
  name: Davie Hodge
  url: www.syftkogtech.com
  email: daviehodge@syftkogtech.com
content_rating:
  adult: false
navigation:
  - name: About us and more ...
    url: 'http://bijousfashions.tumblr.com/'
    type: external
content: []
github: true
url: 'https://bijousfashions.biz'
