layout_spectrum: 0.9507777405732154
typography_spectrum: 0.28678773314950273
color:
  brandColors:
    - '#000000'
    - '#E4BC81'
    - '#C28453'
    - '#007265'
    - '#CD1F16'
  brandStrength: 0.47471338055714374
  lightness: 0.1988473402083584
  saturation: 0.11936995880300234
  rhythmicContrast: 0.009326572366298573
name: BIJOU'S FASHIONS
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4f9abb5-eacd-46a9-9dce-4e7096397a85.jpg
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: 'https://m.facebook.com/BijousFashions/'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/755b1ecf-ff98-4ace-a9f1-cce3388393ab.jpg
purpose: []
title: Bijou's is the Seamless Merger of you and Elegant Accessories
description: ''
author:
  name: Davie Hodge
  url: www.syftkogtech.com
  email: daviehodge@syftkogtech.com
content_rating:
  adult: false
navigation:
  - name: About us and more ...
    url: 'http://bijousfashions.tumblr.com/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/376f9b7634c3eefa1cec25ff4eaf089df1996506">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/376f9b7634c3eefa1cec25ff4eaf089df1996506
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/fd0d9b779a8f414290baa53dddb00e97/noop?input=https%3A%2F%2Fwww.filepicker.io%2Fapi%2Ffile%2Fw8C0rat3RUeQ5Xet2Hta
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
url: 'https://bijousfashions.biz'
