name: "BIJOU'S FASHIONS"
favicon: null
layout_spectrum: 0.1844101424794644
typography_spectrum: 0.7149277641437948
title: "Bijou's is the Seamless Merger of you and Elegant Accessories"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#090b08'
    - '#30322d'
    - '#87a0c6'
    - '#d6c1d4'
  brandStrength: 0.7853818305302411
  lightness: 0.26302918535657227
  saturation: 0.375
  rhythmicContrast: 0.5880552039016038
purpose: []
