layout_spectrum: 0.9507777405732154
typography_spectrum: 0.28678773314950273
color:
  brandColors:
    - '#000000'
    - '#E4BC81'
    - '#C28453'
    - '#007265'
    - '#CD1F16'
  brandStrength: 0.47471338055714374
  lightness: 0.1988473402083584
  saturation: 0.11936995880300234
  rhythmicContrast: 0.009326572366298573
name: BIJOU'S FASHIONS
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4f9abb5-eacd-46a9-9dce-4e7096397a85.jpg
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: 'https://m.facebook.com/BijousFashions/'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/755b1ecf-ff98-4ace-a9f1-cce3388393ab.jpg
purpose:
  - type: contact
    url: 'mailto:sheena@bijousfashions.biz'
    label: Contact me
title: Bijou's is the Seamless Merger of you and Elegant Accessories
description: ''
author:
  name: Davie Hodge
  url: www.syftkogtech.com
  email: daviehodge@syftkogtech.com
content_rating:
  adult: false
navigation:
  - name: About us and more ...
    url: 'http://bijousfashions.tumblr.com/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/8784d8036cd0a3c32df60e3c76694c56e37fd9ba.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/8784d8036cd0a3c32df60e3c76694c56e37fd9ba.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/32a1561965a68076af39bf897da504e3/noop.jpg?input=http%3A%2F%2F78.media.tumblr.com%2F85e91512e6f6478ffe391311ea19a334%2Ftumblr_ozeop6pHc71r24v54o1_1280.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
url: 'https://bijousfashions.biz'
